const BASE_DOMAIN = process.env.BASE_DOMAIN;
const APP_DOMAIN = process.env.APP_DOMAIN;
const SITE_NAME = "OneChatting";
const SITE_LOGO = `${BASE_DOMAIN}/logo-main.png`;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

const TEMPLATE_CHARGES = {
    marketing: 0.20,
    utility: 0.20,
    authentication: 0.20
};

const TURNSTILE_SITE_KEY = process.env.TURNSTILE_SITE_KEY;
const TURNSTILE_SECRET_KEY = process.env.TURNSTILE_SECRET_KEY;

const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = process.env.SMTP_PORT;
const SMTP_SECURE = process.env.SMTP_SECURE === "true";
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const SMTP_FROM = process.env.SMTP_FROM;

const FAST2SMS_API_KEY = process.env.FAST2SMS_API_KEY;
const FAST2SMS_SENDER_ID = process.env.FAST2SMS_SENDER_ID;
const FAST2SMS_URL = process.env.FAST2SMS_URL;
const FAST2SMS_OTP_TEMPLATE = process.env.FAST2SMS_OTP_TEMPLATE;
const ONECHATTING_TEMPLATE_TOKEN = process.env.ONECHATTING_TEMPLATE_TOKEN;
const ONECHATTING_SEND_TOKEN = process.env.ONECHATTING_SEND_TOKEN;
const ONECHATTING_SEND_URL = process.env.ONECHATTING_SEND_URL;

export { 
    BASE_DOMAIN, GOOGLE_CLIENT_ID, 
    TEMPLATE_CHARGES, TURNSTILE_SITE_KEY, TURNSTILE_SECRET_KEY, SMTP_HOST, 
    SMTP_PORT, SMTP_SECURE, SMTP_USER, SMTP_PASS, SMTP_FROM, SITE_NAME, 
    SITE_LOGO, APP_DOMAIN, FAST2SMS_API_KEY, FAST2SMS_SENDER_ID, FAST2SMS_URL, 
    FAST2SMS_OTP_TEMPLATE, ONECHATTING_TEMPLATE_TOKEN, ONECHATTING_SEND_TOKEN, 
    ONECHATTING_SEND_URL 
};
